#!/bin/bash

# Defaults
fontSize=15
trainingLines=./traininglines.txt

_scriptRoot="$(dirname $(realpath $0))"
cd "${_scriptRoot}"

while [ $# -gt 0 ]
do
  case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
    -font)
      fontFile="$2"
      echo "Using font file: ${fontFile}"
      shift
    ;;
    -traininglines)
      trainingLines="$2"
      echo "Using custom traininglines file: ${trainingLines}"
      shift
    ;;
    -fontsize)
      fontSize="$2"
      echo "Generating tifs with custom font size: ${fontSize}"
      shift
    ;;
  esac
  shift
done

# Validate the given -font argument has been set and that the file exists.
if [ -z "${fontFile}" ]
then
  echo "Need a '-font filename' to train"
  exit 1
elif ! [ -f "${fontFile}" ]
then
  echo "Given font :${fontFile}: does not exist."
  exit 1
fi

# Validate that the default traininglines file or a custom -traininglines file has been provided and exists.
if [ -z "${trainingLines}" ]
then
  echo "Need a '-font filename' to train"
  exit 1
elif ! [ -f "${trainingLines}" ]
then
  echo "Wordlist file :${trainingLines}: doesn't exist."
  echo "Create one with lines of text you wish to train against or specify a different file with '-traininglines filename'"
  exit 1
fi

# Get or update tesstrain
if ! [ -d "tesstrain" ]
then
  git clone https://github.com/tesseract-ocr/tesstrain
else
  git -C tesstrain pull
fi

# Use cv2 instead of PIL.Image to generate boxes from our tif's (PIL.Image doesn't seem to support tif's)
#git -C tesstrain apply cv2.patch

fontFileBasename="$(basename "${fontFile}")"
fontFileNoSuffix="${fontFile/.*/}"
fontFileGroundTruthDir="${fontFileNoSuffix}-ground-truth"


# Make a training directory
mkdir -p tesstrain/data/${fontFileGroundTruthDir}

# Generate some tifs to train our traineddata file.
inc=0
while read textLine
do
  convert -background black \
          -fill white \
          -font ${fontFile} \
          -pointsize ${fontSize} \
          label:"${textLine}" \
          -depth 8 \
          tesstrain/data/${fontFileGroundTruthDir}/${inc}.tif

  # Create a text file of the image text to train against.
  echo "${textLine}" > tesstrain/data/${fontFileGroundTruthDir}/${inc}.gt.txt
  ((inc++))
done < ${trainingLines}


# Start training.
echo "Beginning training for ${fontFile} with text lines generated from ${trainingLines}"
cd tesstrain && make training MODEL_NAME=${fontFileNoSuffix}
